export const REPOSITORIES_ROUTES = {
  account: "/account",
  accounts: "/accounts/search",
  courses: "/courses",
  course: "/course",
  coursesProcess: "/courses/process",
  courseProcess: "/course/process",
  courseTasks: "/course/tasks",
  lessons: "/lessons",
  lesson: "/lesson",
  module: "/module",
  tasks: "/tasks",
  task: "/task",
  taskCompleted: "/task/completed",
  taskCompletedComment: "/task/completed/comment",
  group: "/group",
  groups: "/groups",
} as const;
